login: your@login.com
password: youtpassword
playlist_link: http://xvideos.com/favorite/1111111111/
download_path: ./downloads/
user_agent: Mozilla/5.0 (Linux; Android 6.0; FRD-L09 Build/HUAWEIFRD-L09) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/55.0.2883.91 Mobile Safari/537.36